"""Validate every topic file listed in blackout/topics/index.json and regenerate the review sheets.

Run from the repo root:  python tools/check-topics.py

Checks: unique ids across all sets, option counts, option length, fixed-order options match a + d,
multi questions have 2 or more correct, single questions have exactly 4 options, 10 to 15 questions.
Writes docs/review/<group>-questions.md, one sheet per fact-sheet (articles) or per topic (foundations).
"""
import json, os, sys, re, io, collections

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TOPICS = os.path.join(ROOT, 'blackout', 'topics')
REVIEW = os.path.join(ROOT, 'docs', 'review')

def load(name):
    with open(os.path.join(TOPICS, name), encoding='utf-8') as f:
        return json.load(f)

def check(topic, problems, seen_ids):
    for q in topic['questions']:
        if q['id'] in seen_ids:
            problems.append(f"{q['id']}: duplicate question id (also in {seen_ids[q['id']]})")
        seen_ids[q['id']] = topic['id']
    n = len(topic['questions'])
    if not 10 <= n <= 15:
        problems.append(f"{topic['id']}: {n} questions (want 10 to 15)")
    for q in topic['questions']:
        multi = q['type'] == 'multi'
        correct = q['a'] if multi else [q['a']]
        opts = correct + q['d']
        if multi and (not isinstance(q['a'], list) or len(q['a']) < 2):
            problems.append(f"{q['id']}: multi needs 2 or more correct")
        if multi and not 4 <= len(opts) <= 8:
            problems.append(f"{q['id']}: multi has {len(opts)} options (want 4 to 8)")
        if not multi and (not isinstance(q['a'], str) or len(opts) != 4):
            problems.append(f"{q['id']}: single needs exactly 4 options")
        if len(set(opts)) != len(opts):
            problems.append(f"{q['id']}: duplicate options")
        for o in opts:
            if len(o) > 95:
                problems.append(f"{q['id']}: option over 95 chars: {o[:40]}...")
        if q.get('order') == 'fixed':
            if 'options' not in q or set(q['options']) != set(opts) or len(q['options']) != len(opts):
                problems.append(f"{q['id']}: fixed order but options list does not match a + d")
        elif 'options' in q:
            problems.append(f"{q['id']}: has options list but order is not fixed")
        if not q.get('why'):
            problems.append(f"{q['id']}: missing explanation")
        if q.get('difficulty') not in (1, 2, 3):
            problems.append(f"{q['id']}: difficulty must be 1, 2 or 3")

def sheet(topics):
    out = io.StringIO()
    out.write('# Review sheet\n\nOne line per question: id, type, difficulty, the question, then the correct answer(s). '
              'Options marked fixed are shown in the order listed. Generated by tools/check-topics.py from the topic files; edit those, not this.\n')
    for t in topics:
        out.write(f"\n## {t['title']} ({len(t['questions'])} questions)\n\n")
        out.write(f"Source: {t.get('source', {}).get('citation', 'none')}\n\n")
        for q in t['questions']:
            a = q['a'] if isinstance(q['a'], str) else ' + '.join(q['a'])
            n = len(q['d']) + (1 if isinstance(q['a'], str) else len(q['a']))
            fx = ', fixed order' if q.get('order') == 'fixed' else ''
            out.write(f"- **{q['id']}** ({q['type']}, d{q['difficulty']}, {n} options{fx}) {q['q']}\n  → {a}\n")
    return out.getvalue()

def main():
    index = load('index.json')
    problems, seen_ids = [], {}
    groups = collections.OrderedDict()
    total = 0
    for st in index['sets']:
        for name in st['topics']:
            t = load(name)
            check(t, problems, seen_ids)
            total += len(t['questions'])
            m = re.search(r'docs/facts/([\w-]+)\.md', t.get('source', {}).get('facts', '') or '')
            key = m.group(1) if m else f"{st['id']}-{t['id']}"
            groups.setdefault(key, []).append(t)
    os.makedirs(REVIEW, exist_ok=True)
    for key, ts in groups.items():
        with open(os.path.join(REVIEW, f'{key}-questions.md'), 'w', encoding='utf-8') as f:
            f.write(sheet(ts))
    print(f"{len(index['sets'])} sets, {len(seen_ids) and sum(len(v) for v in groups.values())} topics, {total} questions, {len(groups)} review sheets")
    if problems:
        print('\n'.join(problems))
        sys.exit(1)
    print('all checks passed')

if __name__ == '__main__':
    main()
